// <auto-generated />
namespace Red_Lake_Hospital_Redesign_Team6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FEEDBACKUPDATE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FEEDBACKUPDATE));
        
        string IMigrationMetadata.Id
        {
            get { return "202104302002437_FEEDBACK-UPDATE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
